Remove unused code
0xd4d/dnSpy pull request #1579
Opened 2020-09-15 02:49 UTC by Symbai

2020-09-15 06:30 UTC, 0xd4d requested changes

2020-09-15 06:30 UTC, 0xd4d commented on dnSpy/dnSpy.Contracts.DnSpy/Themes/ColorType.cs
> -		SearchBoxWatermark,
Removing an enum field is a breaking change.

2020-09-15 16:58 UTC, 0xd4d approved these changes

2020-09-15 16:58 UTC, merged

2020-09-21 23:09 UTC, rickbrew commented
Thanks @0xd4d , it works now!